/****** Script for Updating and Inserting Card Types in PAY005 Table ******/
BEGIN TRAN
-- 1. Update Visa to VISA
UPDATE PAY005
SET C_CARDTYPE = 'VISA'
WHERE C_CARDTYPE = 'Visa';
-- 2. Insert VISA_DEBIT
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT 
    I_PAY003FK, 'VISA_DEBIT', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'VISA';
-- Verify VISA_DEBIT insertion
SELECT * 
FROM PAY005 
WHERE C_CARDTYPE = 'VISA_DEBIT';
-- 3. Update MasterCard to MC
UPDATE PAY005
SET C_CARDTYPE = 'MC'
WHERE C_CARDTYPE = 'MasterCard';
-- 4. Insert MC_DEBIT
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT 
    I_PAY003FK, 'MC_DEBIT', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'MC';
-- Verify MC_DEBIT insertion
SELECT * 
FROM PAY005 
WHERE C_CARDTYPE = 'MC_DEBIT';
-- 5. Update AmericanExpress to AMEX
UPDATE PAY005
SET C_CARDTYPE = 'AMEX'
WHERE C_CARDTYPE = 'AmericanExpress';
-- 6. Update Discover to DISC
UPDATE PAY005
SET C_CARDTYPE = 'DISC'
WHERE C_CARDTYPE = 'Discover';
-- 7. Insert DISC_DEBIT
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT 
    I_PAY003FK, 'DISC_DEBIT', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'DISC';
-- Verify DISC_DEBIT insertion
SELECT * 
FROM PAY005 
WHERE C_CARDTYPE = 'DISC_DEBIT';
-- 8. Update eCheck to CHQ
UPDATE PAY005
SET C_CARDTYPE = 'CHQ'
WHERE C_CARDTYPE = 'eCheck';
-- 9. Insert SAV for CHQ
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT 
    I_PAY003FK, 'SAV', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'CHQ';
-- 10. Update PayPal to PAYPAL
UPDATE PAY005
SET C_CARDTYPE = 'PAYPAL'
WHERE C_CARDTYPE = 'PayPal';
-- 11. Insert PAYPAL_CREDIT and PAYPAL_ACCOUNT
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT 
    I_PAY003FK, 'PAYPAL_CREDIT', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'PAYPAL';
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT 
    I_PAY003FK, 'PAYPAL_ACCOUNT', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'PAYPAL';
-- 12. Update Walmart Pay, Venmo, GooglePay and ApplePay
UPDATE PAY005
SET C_CARDTYPE = 'WALMART_PAY'
WHERE C_CARDTYPE = 'WalmartPay';
UPDATE PAY005
SET C_CARDTYPE = 'VENMO'
WHERE C_CARDTYPE = 'Venmo';
UPDATE PAY005
SET C_CARDTYPE = 'GP'
WHERE C_CARDTYPE = 'GooglePay';
UPDATE PAY005
SET C_CARDTYPE = 'AP'
WHERE C_CARDTYPE = 'ApplePay';
-- 13. Update POS
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT TOP 1
    I_PAY003FK, 'CP_POS_AMEX', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'AMEX' AND C_TRANSACTIONCODE='DEP2';
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT TOP 1
    I_PAY003FK, 'CP_POS_DISC', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'DISC' AND C_TRANSACTIONCODE='DEP2';
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT TOP 1
    I_PAY003FK, 'CP_POS_DISC_DEBIT', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'DISC_DEBIT' AND C_TRANSACTIONCODE='DEP2';
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT TOP 1
    I_PAY003FK, 'CP_POS_MC', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'MC' AND C_TRANSACTIONCODE='DEP2';
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT TOP 1
    I_PAY003FK, 'CP_POS_MC_DEBIT', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'MC_DEBIT' AND C_TRANSACTIONCODE='DEP2';
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT TOP 1
    I_PAY003FK, 'CP_POS_VISA', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'VISA' AND C_TRANSACTIONCODE='DEP2';
INSERT INTO PAY005 (I_PAY003FK, C_CARDTYPE, C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE)
SELECT DISTINCT TOP 1
    I_PAY003FK, 'CP_POS_VISA_DEBIT', C_DESCRIPTION, C_TRANSACTIONCODE, C_EXTERNALSOURCE
FROM PAY005
WHERE C_CARDTYPE = 'VISA_DEBIT' AND C_TRANSACTIONCODE='DEP2';

-- Final verification for all new card types
SELECT *
FROM PAY005
WHERE C_CARDTYPE IN (
    'VISA_DEBIT', 'MC_DEBIT', 'DISC_DEBIT', 'SAV', 
    'PAYPAL_CREDIT', 'PAYPAL_ACCOUNT', 'WALMART_PAY',
    'VENMO', 'GP', 'AP'
);

-- Final confirmation
SELECT * FROM PAY005;
COMMIT TRAN