INSERT INTO PAY005 (
    I_PAY003FK,
    C_CARDTYPE,
    C_DESCRIPTION,
    C_TRANSACTIONCODE,
    C_EXTERNALSOURCE
) VALUES 
    (1, 'AmericanExpress', 'Payment - IVR - credit card - AmericanExpress', 'PAY4', 'IVR'),
(1, 'MasterCard', 'Payment - IVR - credit card - MasterCard', 'PAY4', 'IVR'),
(1, 'Discover', 'Payment - IVR - credit card - Discover', 'PAY4', 'IVR'),
(1, 'e-check/ACH', 'Waterworks - One Time Donation-Cashier - e-check/ACH', 'WW03', 'IVR'),
(1, 'AmericanExpress', 'Waterworks - One Time Donation-Cashier - AmericanExpress', 'WW03', 'IVR'),
(1, 'Visa', 'Waterworks - One Time Donation-Cashier - Visa', 'WW03', 'IVR'),
(1, 'MasterCard', 'Waterworks - One Time Donation-Cashier - MasterCard', 'WW03', 'IVR'),
(1, 'Discover', 'Waterworks - One Time Donation-Cashier - Discover', 'WW03', 'IVR'),
(1, 'e-check/ACH', 'Hydrant Deposit Paid - e-check/ACH', 'DEP1', 'IVR'),
(1, 'AmericanExpress', 'Hydrant Deposit Paid - AmericanExpress', 'DEP1', 'IVR'),
(1, 'Visa', 'Hydrant Deposit Paid - Visa', 'DEP1', 'IVR'),
(1, 'MasterCard', 'Hydrant Deposit Paid - MasterCard', 'DEP1', 'IVR'),
(1, 'Discover', 'Hydrant Deposit Paid - Discover', 'DEP1', 'IVR'),
(1, 'e-check/ACH', 'Payment - Cashier or Payment -AA IVR - e-check/ACH', 'PAYM', 'AD'),
(1, 'Discover', 'Payment - Cashier or Payment -AA IVR - Discover', 'PAY1', 'AD'),
(1, 'e-check/ACH', 'Waterworks - One Time Donation-Cashier - e-check/ACH', 'WW03', 'AD'),
(1, 'AmericanExpress', 'Waterworks - One Time Donation-Cashier - AmericanExpress', 'WW03', 'AD'),
(1, 'Visa', 'Waterworks - One Time Donation-Cashier - Visa', 'WW03', 'AD'),
(1, 'MasterCard', 'Waterworks - One Time Donation-Cashier - MasterCard', 'WW03', 'AD'),
(1, 'Discover', 'Waterworks - One Time Donation-Cashier - Discover', 'WW03', 'AD'),
(1, 'e-check/ACH', 'Hydrant Deposit Paid - e-check/ACH', 'DEP1', 'AD'),
(1, 'AmericanExpress', 'Hydrant Deposit Paid - AmericanExpress', 'DEP1', 'AD'),
(1, 'Visa', 'Hydrant Deposit Paid - Visa', 'DEP1', 'AD'),
(1, 'MasterCard', 'Hydrant Deposit Paid - MasterCard', 'DEP1', 'AD'),
(1, 'Discover', 'Hydrant Deposit Paid - Discover', 'DEP1', 'AD'),
(1, 'AmericanExpress', 'Payment - POS - AmericanExpress', 'PAYV', 'AD'),
(1, 'Visa', 'Payment - POS - Visa', 'PAYV', 'AD'),
(1, 'MasterCard', 'Payment - POS - MasterCard', 'PAYV', 'AD'),
(1, 'Discover', 'Payment - POS - Discover', 'PAYV', 'AD'),
(1, 'e-check/ACH', 'Waterworks - One Time Donation-POS- e-check/ACH', 'WW06', 'AD'),
(1, 'AmericanExpress', 'Waterworks - One Time Donation-POS- AmericanExpress', 'WW06', 'AD'),
(1, 'Visa', 'Waterworks - One Time Donation-POS- Visa', 'WW06', 'AD'),
(1, 'MasterCard', 'Waterworks - One Time Donation-POS- MasterCard', 'WW06', 'AD'),
(1, 'Discover', 'Waterworks - One Time Donation-POS- Discover', 'WW06', 'AD'),
(1, 'e-check/ACH', 'Hydrant Deposit Paid - POS - e-check/ACH', 'DEP2', 'AD'),
(1, 'AmericanExpress', 'Hydrant Deposit Paid - POS - AmericanExpress', 'DEP2', 'AD'),
(1, 'Visa', 'Hydrant Deposit Paid - POS - Visa', 'DEP2', 'AD'),
(1, 'MasterCard', 'Hydrant Deposit Paid - POS - MasterCard', 'DEP2', 'AD'),
(1, 'Discover', 'Hydrant Deposit Paid - POS - Discover', 'DEP2', 'AD'),
(1, 'e-check/ACH', 'Payment - Paymentus One-time e-check - e-check/ACH', 'PAYK', 'WEB'),
(1, 'AmericanExpress', 'Payment - Paymentus One-time - AmericanExpress', 'PAYZ', 'WEB'),
(1, 'Visa', 'Payment - Paymentus One-time - Visa', 'PAYZ', 'WEB'),
(1, 'MasterCard', 'Payment - Paymentus One-time - MasterCard', 'PAYZ', 'WEB'),
(1, 'Discover', 'Payment - Paymentus One-time - Discover', 'PAYZ', 'WEB'),
(1, 'PayPal credit', 'Payment - Paymentus One-time - Paypal Credit', 'PAYZ', 'WEB'),
(1, 'PayPal application', 'Payment - Paymentus One-time - Paypal application', 'PAYZ', 'WEB'),
(1, 'VENMO', 'Payment - Paymentus One-time - VENMO', 'PAYZ', 'WEB'),
(1, 'Apple Pay', 'Payment - Paymentus One-time - Apple Pay', 'PAYZ', 'WEB'),
(1, 'Google_PAY', 'Payment - Paymentus One-time - Google_PAY', 'PAYZ', 'WEB'),
(1, 'Amazon Pay', 'Payment - Paymentus One-time - Amazon Pay', 'PAYZ', 'WEB'),
(1, 'e-check/ACH', 'Waterworks - One Time Donation-Cashier - e-check/ACH', 'WW03', 'WEB'),
(1, 'AmericanExpress', 'Waterworks - One Time Donation-Cashier - AmericanExpress', 'WW03', 'WEB'),
(1, 'Visa', 'Waterworks - One Time Donation-Cashier - Visa', 'WW03', 'WEB'),
(1, 'MasterCard', 'Waterworks - One Time Donation-Cashier - MasterCard', 'WW03', 'WEB'),
(1, 'Discover', 'Waterworks - One Time Donation-Cashier - Discover', 'WW03', 'WEB'),
(1, 'PayPal credit', 'Payment - Paymentus One-time - Paypal Credit', 'WW03', 'WEB'),
(1, 'PayPal application', 'Payment - Paymentus One-time - Paypal application', 'WW03', 'WEB'),
(1, 'VENMO', 'Payment - Paymentus One-time - VENMO', 'WW03', 'WEB'),
(1, 'Apple Pay', 'Payment - Paymentus One-time - Apple Pay', 'WW03', 'WEB'),
(1, 'Google_PAY', 'Payment - Paymentus One-time - Google_PAY', 'WW03', 'WEB'),
(1, 'Amazon Pay', 'Payment - Paymentus One-time - Amazon Pay', 'WW03', 'WEB'),
(1, 'e-check/ACH', 'Hydrant Deposit Paid - e-check/ACH', 'DEP1', 'WEB'),
(1, 'AmericanExpress', 'Hydrant Deposit Paid - AmericanExpress', 'DEP1', 'WEB'),
(1, 'Visa', 'Hydrant Deposit Paid - Visa', 'DEP1', 'WEB'),
(1, 'MasterCard', 'Hydrant Deposit Paid - MasterCard', 'DEP1', 'WEB'),
(1, 'Discover', 'Hydrant Deposit Paid - Discover', 'DEP1', 'WEB'),
(1, 'PayPal credit', 'Hydrant Deposit Paid - PayPal credit', 'DEP1', 'WEB'),
(1, 'PayPal application', 'Hydrant Deposit Paid - PayPal application', 'DEP1', 'WEB'),
(1, 'VENMO', 'Hydrant Deposit Paid - VENMO', 'DEP1', 'WEB'),
(1, 'Apple Pay', 'Hydrant Deposit Paid - Apple Pay', 'DEP1', 'WEB'),
(1, 'Google_PAY', 'Hydrant Deposit Paid - Google_PAY', 'DEP1', 'WEB'),
(1, 'Amazon Pay', 'Hydrant Deposit Paid - Amazon Pay', 'DEP1', 'WEB'),
(1, 'e-check/ACH', 'Payment - Paymentus Portal e-check - e-check/ACH', 'PAYB', 'CP_WEB'),
(1, 'AmericanExpress', 'Payment - Paymentus Portal - AmericanExpress', 'PAYP', 'CP_WEB'),
(1, 'Visa', 'Payment - Paymentus Portal - Visa', 'PAYP', 'CP_WEB'),
(1, 'MasterCard', 'Payment - Paymentus Portal - MasterCard', 'PAYP', 'CP_WEB'),
(1, 'Discover', 'Payment - Paymentus Portal - Discover', 'PAYP', 'CP_WEB'),
(1, 'PayPal credit', 'Payment - Paymentus Portal - PayPal credit', 'PAYP', 'CP_WEB'),
(1, 'PayPal application', 'Payment - Paymentus Portal - PayPal application', 'PAYP', 'CP_WEB'),
(1, 'VENMO', 'Payment - Paymentus Portal - VENMO', 'PAYP', 'CP_WEB'),
(1, 'Apple Pay', 'Payment - Paymentus Portal - Apple Pay', 'PAYP', 'CP_WEB'),
(1, 'Google_PAY', 'Payment - Paymentus Portal - Google_PAY', 'PAYP', 'CP_WEB'),
(1, 'Amazon Pay', 'Payment - Paymentus Portal - Amazon Pay', 'PAYP', 'CP_WEB'),
(1, 'e-check/ACH', 'Waterworks - One Time Donation-Cashier - e-check/ACH', 'WW03', 'CP_WEB'),
(1, 'AmericanExpress', 'Waterworks - One Time Donation-Cashier - AmericanExpress', 'WW03', 'CP_WEB'),
(1, 'Visa', 'Waterworks - One Time Donation-Cashier - Visa', 'WW03', 'CP_WEB'),
(1, 'MasterCard', 'Waterworks - One Time Donation-Cashier - MasterCard', 'WW03', 'CP_WEB'),
(1, 'Discover', 'Waterworks - One Time Donation-Cashier - Discover', 'WW03', 'CP_WEB'),
(1, 'PayPal credit', 'Payment - Paymentus One-time - Paypal Credit', 'WW03', 'CP_WEB'),
(1, 'PayPal application', 'Payment - Paymentus One-time - Paypal application', 'WW03', 'CP_WEB'),
(1, 'VENMO', 'Payment - Paymentus One-time - VENMO', 'WW03', 'CP_WEB'),
(1, 'Apple Pay', 'Payment - Paymentus One-time - Apple Pay', 'WW03', 'CP_WEB'),
(1, 'Google_PAY', 'Payment - Paymentus One-time - Google_PAY', 'WW03', 'CP_WEB'),
(1, 'Amazon Pay', 'Payment - Paymentus One-time - Amazon Pay', 'WW03', 'CP_WEB'),
(1, 'e-check/ACH', 'Hydrant Deposit Paid - e-check/ACH', 'DEP1', 'CP_WEB'),
(1, 'AmericanExpress', 'Hydrant Deposit Paid - AmericanExpress', 'DEP1', 'CP_WEB'),
(1, 'Visa', 'Hydrant Deposit Paid - Visa', 'DEP1', 'CP_WEB'),
(1, 'MasterCard', 'Hydrant Deposit Paid - MasterCard', 'DEP1', 'CP_WEB'),
(1, 'Discover', 'Hydrant Deposit Paid - Discover', 'DEP1', 'CP_WEB'),
(1, 'PayPal credit', 'Hydrant Deposit Paid - PayPal credit', 'DEP1', 'CP_WEB'),
(1, 'PayPal application', 'Hydrant Deposit Paid - PayPal application', 'DEP1', 'CP_WEB'),
(1, 'VENMO', 'Hydrant Deposit Paid - VENMO', 'DEP1', 'CP_WEB'),
(1, 'Apple Pay', 'Hydrant Deposit Paid - Apple Pay', 'DEP1', 'CP_WEB'),
(1, 'Google_PAY', 'Hydrant Deposit Paid - Google_PAY', 'DEP1', 'CP_WEB'),
(1, 'Amazon Pay', 'Hydrant Deposit Paid - Amazon Pay', 'DEP1', 'CP_WEB'),
(1, 'e-check/ACH', 'Payment - Autopay e-check - e-check/ACH', 'PAY3', 'SCHEDULED'),
(1, 'AmericanExpress', 'Payment - Autopay - AmericanExpress', 'PAYD', 'SCHEDULED'),
(1, 'Visa', 'Payment - Autopay - Visa', 'PAYD', 'SCHEDULED'),
(1, 'MasterCard', 'Payment - Autopay - MasterCard', 'PAYD', 'SCHEDULED'),
(1, 'Discover', 'Payment - Autopay - Discover', 'PAYD', 'SCHEDULED'),
(1, 'PayPal credit', 'Payment - Autopay - PayPal credit', 'PAYD', 'SCHEDULED'),
(1, 'PayPal application', 'Payment - Autopay - PayPal application', 'PAYD', 'SCHEDULED'),
(1, 'VENMO', 'Payment - Autopay - VENMO', 'PAYD', 'SCHEDULED'),
(1, 'Apple Pay', 'Payment - Autopay - Apple Pay', 'PAYD', 'SCHEDULED'),
(1, 'Google_PAY', 'Payment - Autopay - Google_PAY', 'PAYD', 'SCHEDULED'),
(1, 'Amazon Pay', 'Payment - Autopay - Amazon Pay', 'PAYD', 'SCHEDULED'),
(1, 'e-check/ACH', 'Payment - Autopay e-check - e-check/ACH', 'PAYF', 'SCHEDULED'),
(1, 'AmericanExpress', 'Payment - Autopay - AmericanExpress', 'PAYF', 'SCHEDULED'),
(1, 'Visa', 'Payment - Autopay - Visa', 'PAYF', 'SCHEDULED'),
(1, 'MasterCard', 'Payment - Autopay - MasterCard', 'PAYF', 'SCHEDULED'),
(1, 'Discover', 'Payment - Autopay - Discover', 'PAYF', 'SCHEDULED'),
(1, 'PayPal credit', 'Payment - Autopay - PayPal credit', 'PAYF', 'SCHEDULED'),
(1, 'PayPal application', 'Payment - Autopay - PayPal application', 'PAYF', 'SCHEDULED'),
(1, 'VENMO', 'Payment - Autopay - VENMO', 'PAYF', 'SCHEDULED'),
(1, 'Apple Pay', 'Payment - Autopay - Apple Pay', 'PAYF', 'SCHEDULED'),
(1, 'Google_PAY', 'Payment - Autopay - Google_PAY', 'PAYF', 'SCHEDULED'),
(1, 'Amazon Pay', 'Payment - Autopay - Amazon Pay', 'PAYF', 'SCHEDULED'),
(1, 'Cash', 'Payment - Walmart - Cash', 'PAYW', 'IPN')
;