-- =============================================
-- Script: Fix missing SYS1 transactions for CB bills
-- Description: Identifies and inserts missing SYS1 transactions for cancelled bills
-- Created: 01/29/2024
-- =============================================

-- CREATE BACKUP TABLE
IF OBJECT_ID('ADVANCED.BIF955BAK_01292024', 'U') IS NULL
BEGIN
    SELECT * INTO ADVANCED.BIF955BAK_01292024 FROM ADVANCED.BIF955;
    PRINT 'Backup table ADVANCED.BIF955BAK_01292024 created successfully.';
END
ELSE
BEGIN
    PRINT 'Backup table ADVANCED.BIF955BAK_01292024 already exists.';
END
GO

-- CREATE TEMP TABLE WITH PROPER STRUCTURE
IF OBJECT_ID('ADVANCED.TEMP_SYS1', 'U') IS NOT NULL
    DROP TABLE ADVANCED.TEMP_SYS1;

SELECT TOP 0 * INTO ADVANCED.TEMP_SYS1 FROM ADVANCED.BIF955;

-- Verify temp table exists and is empty
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'ADVANCED' AND TABLE_NAME = 'TEMP_SYS1')
BEGIN
    DECLARE @RecordCount INT;
    SELECT @RecordCount = COUNT(*) FROM ADVANCED.TEMP_SYS1;
    PRINT 'TEMP_SYS1 table created successfully. Current record count: ' + CAST(@RecordCount AS VARCHAR(10));
END
ELSE
BEGIN
    RAISERROR('Failed to create TEMP_SYS1 table', 16, 1);
    RETURN;
END
GO

-- COUNT NUMBER OF BILLS NEEDING FIX
DECLARE @RecordsToFix INT;

SELECT @RecordsToFix = COUNT(*)
FROM ADVANCED.BIF951 A 
LEFT JOIN ADVANCED.BIF955 B 
    ON A.I_BILLNUMBER = B.I_BILLNUMBER 
    AND B.C_TRANSCODE = 'SYS1'
LEFT JOIN ADVANCED.BIF951 C 
    ON A.I_ORGBILL = C.I_BILLNUMBER
WHERE A.C_BILLTYPE = 'CB' 
    AND A.L_PROCESSED = 1 
    AND B.C_TRANSCODE IS NULL
    AND A.D_BILLDATE >= '2021-01-01';

PRINT 'Number of records needing fix: ' + CAST(@RecordsToFix AS VARCHAR(10));
GO

-- INSERT RECORDS INTO TEMP TABLE
DECLARE @InsertedRows INT;

INSERT INTO ADVANCED.TEMP_SYS1 (
    I_BILLNUMBER, 
    I_BATCHID, 
    C_ACCOUNT, 
    T_TRANSDT, 
    C_TRANSCODE, 
    N_AMOUNT, 
    I_TRANSNUM, 
    C_USERID, 
    L_BIF042, 
    N_SUMFLAG, 
    L_PENALTY, 
    L_HIDDEN, 
    C_ARCODE, 
    C_SUPPLIER, 
    L_SYS_HIDE, 
    C_SERVICE, 
    L_CANCELSECTION, 
    N_WAP, 
    I_ORIGTRAN, 
    N_SORT, 
    L_TAXED, 
    I_LOANNUM, 
    I_ORIGBILL
)
SELECT 
    A.I_BILLNUMBER, 
    A.I_BATCHID, 
    A.C_ACCOUNT, 
    A.D_BILLDATE AS T_TRANSDT, 
    'SYS1' AS C_TRANSCODE, 
    C.Y_AMOUNTDUEBEFOREDUEDATE AS N_AMOUNT,
    -1 AS I_TRANSNUM, 
    A.C_USERID, 
    1 AS L_BIF042, 
    0 AS N_SUMFLAG, 
    0 AS L_PENALTY, 
    0 AS L_HIDDEN, 
    '' AS C_ARCODE, 
    '' AS C_SUPPLIER, 
    0 AS L_SYS_HIDE, 
    '' AS C_SERVICE, 
    0 AS L_CANCELSECTION, 
    0 AS N_WAP, 
    2 AS I_ORIGTRAN, 
    2 AS N_SORT, 
    1 AS L_TAXED, 
    0 AS I_LOANNUM, 
    0 AS I_ORIGBILL
FROM ADVANCED.BIF951 A 
LEFT JOIN ADVANCED.BIF955 B 
    ON A.I_BILLNUMBER = B.I_BILLNUMBER 
    AND B.C_TRANSCODE = 'SYS1'
LEFT JOIN ADVANCED.BIF951 C 
    ON A.I_ORGBILL = C.I_BILLNUMBER
WHERE A.C_BILLTYPE = 'CB' 
    AND A.L_PROCESSED = 1 
    AND B.C_TRANSCODE IS NULL
    AND A.D_BILLDATE > '2020-01-01';

SET @InsertedRows = @@ROWCOUNT;
PRINT 'Records inserted into TEMP_SYS1: ' + CAST(@InsertedRows AS VARCHAR(10));
GO

-- VALIDATE TEMP TABLE DATA
PRINT 'Validating TEMP_SYS1 data:';
SELECT 
    COUNT(*) AS TotalRecords,
    AVG(N_AMOUNT) AS AverageAmount,
    MIN(N_AMOUNT) AS MinAmount,
    MAX(N_AMOUNT) AS MaxAmount
FROM ADVANCED.TEMP_SYS1;

-- Sample records for review
SELECT TOP 5 
    I_BILLNUMBER,
    C_ACCOUNT,
    T_TRANSDT,
    N_AMOUNT
FROM ADVANCED.TEMP_SYS1
ORDER BY T_TRANSDT DESC;
GO

-- COPY RECORDS FROM TEMP TABLE TO BIF955
DECLARE @FinalInsertCount INT;

BEGIN TRY
    BEGIN TRANSACTION;
    
    INSERT INTO ADVANCED.BIF955 (
        I_BILLNUMBER, I_BATCHID, C_ACCOUNT, T_TRANSDT, C_TRANSCODE, N_AMOUNT, 
        I_TRANSNUM, C_USERID, L_BIF042, N_SUMFLAG, L_PENALTY, L_HIDDEN, 
        C_ARCODE, C_SUPPLIER, L_SYS_HIDE, C_SERVICE, L_CANCELSECTION, N_WAP, 
        I_ORIGTRAN, N_SORT, L_TAXED, I_LOANNUM, I_ORIGBILL
    )
    SELECT 
        I_BILLNUMBER, I_BATCHID, C_ACCOUNT, T_TRANSDT, C_TRANSCODE, N_AMOUNT,
        I_TRANSNUM, C_USERID, L_BIF042, N_SUMFLAG, L_PENALTY, L_HIDDEN,
        C_ARCODE, C_SUPPLIER, L_SYS_HIDE, C_SERVICE, L_CANCELSECTION, N_WAP,
        I_ORIGTRAN, N_SORT, L_TAXED, I_LOANNUM, I_ORIGBILL
    FROM ADVANCED.TEMP_SYS1;

    SET @FinalInsertCount = @@ROWCOUNT;
    
    COMMIT TRANSACTION;
    
    PRINT 'Successfully inserted ' + CAST(@FinalInsertCount AS VARCHAR(10)) + ' records into BIF955';
    
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;
        
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();
    
    RAISERROR('Error inserting records: %s', @ErrorSeverity, @ErrorState, @ErrorMessage);
    RETURN;
END CATCH
GO

-- FINAL VALIDATION
PRINT 'Final validation - comparing source and target:';

SELECT 
    (SELECT COUNT(*) FROM ADVANCED.TEMP_SYS1) AS TempRecordCount,
    (SELECT COUNT(*) FROM ADVANCED.BIF955 WHERE C_TRANSCODE = 'SYS1' AND I_TRANSNUM = -1) AS NewBIF955Records;

-- CLEANUP: DROP TEMP TABLE
IF OBJECT_ID('ADVANCED.TEMP_SYS1', 'U') IS NOT NULL
BEGIN
    DROP TABLE ADVANCED.TEMP_SYS1;
    PRINT 'TEMP_SYS1 table dropped successfully.';
END
GO

PRINT 'Script execution completed.';